[tool.ruff]
line-length = 100
indent-width = 4
output-format = 'pylint'

[tool.ruff.lint.pylint]
max-branches = 10
max-nested-blocks=4
max-args=6

[tool.ruff.lint] 
select = ["A00", 
          "ARG",  
          "B015", "B018", "B020", "BLE001", 
          "E1", "E5", "E701", "E702", "E703", "E711", "E722", 
          "F", 
          "ISC001",   
          "N", 
          "PLE", "PLR0911", "PLR0912", "PLR0913", "PLR1702", "PLW0603", "PLW1501", "PLW3201", 
          "S307",  
          "RET503",  
          ] 
ignore = ["E115", "E116", "E117", "F401", "E711"] 
preview = true 
